# Generated by Django 3.0.5 on 2020-08-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=300)),
                ('img_src', models.ImageField(upload_to='static/pics/')),
            ],
        ),
    ]
