# Generated by Django 3.0.5 on 2020-08-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200813_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=300)),
                ('video_url', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
